import type { Metadata } from 'next'
import { cn } from '@/lib/utils'
import './globals.css'

import { Inter as FontSans } from 'next/font/google'
import { ThemeProvider } from '@/components/ui/theme-provider'
import Logo from '@/components/sections/Logo'
import NavBar from '@/components/sections/NavBar'
import Header from '@/components/sections/Header'

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
                        <div className="hidden border-r bg-muted/40 md:block">
                            <div className="flex h-full max-h-screen flex-col gap-2">
                                <Logo />
                                <NavBar />
                            </div>
                        </div>
                        <div className="flex flex-col">
                            <Header />
                            <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">{children}</main>
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
